# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.
#
# If you need help with YAML syntax, here are some quick references for you:
# https://learn-the-web.algonquindesign.ca/topics/markdown-yaml-cheat-sheet/#yaml
# https://learnxinyminutes.com/docs/yaml/
#
# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.

title: PowerfulDevs Testing
name: "Grant Archibald"
description: >- # this means to ignore newlines until "baseurl:"
  Mastering Automated Testing in Power Platform. Discussion and examples as Power CAT Engineering apply automated testing and collaborate with Power Platform Engineering teams.
baseurl: "/powerfuldev-testing" # the subpath of your site, e.g. /blog
url: "https://grant-archibald-ms.github.io" # the base hostname & protocol for your site, e.g. http://example.com
github_username:  grant-archibald-ms
enable_copy_code_button: true
minimal_mistakes_skin: air
favicon: /powerfuldev-testing/assets/images/favicon.ico
copyright_url: https://grant-archibald-ms.github.io/powerfuldev-testing
permalink: /:categories/:title/
og_image: "/PowerfulDevConference.png"
permalink: pretty
search: true
search_provider: lunr

lunr:
  search_within_pages: true

author:
  name     : "Grant Archibald"
  bio: "Program Manager in Microsoft Power CAT Engineering"
  links:
    - label: "LinkedIn"
      icon: "fa-brands fa-linkedin"
      url: "https://www.linkedin.com/in/grantarchibald/"
    - label: "Power CAT"
      icon: "fa-brands fa-microsoft"
      url: "https://aka.ms/whoispowercat"

# Build settings
theme: minimal-mistakes-jekyll

plugins:
  - jekyll-feed
  - jekyll-spaceship

gems: [jekyll-mermaid]

logging:
  level: debug

include:
  - context
  - discussion
  - examples
  - assets

copy_folders:
  - source: '../roles-and-responsibilities'
    destination: 'roles-and-responsibilities'
  - source: '../context'
    destination: 'context'
  - source: '../examples'
    destination: 'examples'
  - source: '../discussion'
    destination: 'discussion'

rename_files:
  - from: "_site/discussion.html"
    to: "_site/discussion/index.html"
  - from: "_site/context.html"
    to: "_site/context/index.html"
  - from: "_site/examples.html"
    to: "_site/examples/index.html"
  - from: "_site/roles-and-responsibilities.html"
    to: "_site/roles-and-responsibilities/index.html"

navigation:
  - main
  - docs

exclude:
  - "*.markdown"

sidebar:
  nav: "docs"

defaults:
  - scope:
      path: "discussion"
    values:
      permalink: /discussion/:path/
  - scope:
      path: ""
    values:
      og_image: "/powerfuldev-testing/PowerfulDevConference.png"
  - scope:
      path: "" # An empty string here means all files in the project
      type: "examples" # This applies to all pages
    values:
      layout: single
      og_image: "/powerfuldev-testing/PowerfulDevConference.png"
  - scope:
      path: "" # An empty string here means all files in the project
      type: "discussion" # This applies to all pages
    values:
      layout: single
      og_image: "/powerfuldev-testing/PowerfulDevConference.png"
  - scope:
      path: ""
      type: posts
    values:
      layout: single
      author_profile: true
      read_time: true
      related: true
      og_image: "/powerfuldev-testing/PowerfulDevConference.png"
